[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "operix-engine"
version = "0.1.0"
description = "Motor de análisis de video de Operix."
readme = "README.md"
requires-python = ">=3.12,<3.13"
dependencies = [
    "opencv-python",
    "ultralytics",
]

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]
